language: node_js

node_js:
- '8'
- '11'

services:
  - docker

before_install:
  - docker pull pseudomuto/protoc-gen-doc
  - 

install:
  - npm install

script:
  - npm run build
  - npm test

after_success:
  - docker run --rm  -v $(pwd)/doc:/out -v $(pwd)/proto:/protos pseudomuto/protoc-gen-doc

deploy:
  - provider: npm
    email: thomas@toye.io
    api_key:
      secure: FJ/vMVX2u5CIqXE3rfLaWwq5MCZgEfQC/NjO7e10f1jJsNahD5FfeYK9jRZHJSOBaeMIQp+KV00lildCA5Ro/oGvn/0DJc3evQYj13rNq2aG+4Ij38M6Q2tbOBqZEzfVX/4Im+8M8A8E+mSSE3P6kZPgw+qbFcAXGX67Ouhs8Y3x7PVml/t2aaiMsUASWdsG26UyL3pWgTi1PK4dwi2ovXV5Ed3jxQs7fUyynJiymSyv4ODN0qsRMvF4Rk9Tl0/pXgATfrLD+n7cciTQU1f5oEPgZ9zwMiYHVn1gnzyxnNmZHl0I8KKo/fMnnJvTulmdrl9BhijXvPVjPEG8Q3Dy4RtxRlEqeBaAwjHP6mq3VijkHjybsjY+i88w6CMnWts1jOVrYbowylgR2VExSYJbsRHABY4DJsxAV2bMOLGbLToyyRIQ6muvTisFnA3z+uzLqyGnoTz3vIrN+XI6ED01uVczHrP3z7klhx6N4ETHXL6VbZfl3x3GhyIryWsXfbckBxyaWnBz+yguhcfk+nu21xqw65QluyUbwBiUiQtu4+JirwjkWoBrFG0etRTQJt+1NPGOpnNsDF7nnBA42XtUWO/2K9HBY5OVeO0UWc0Z/FeztRBo0Obd0EWhBx2Jmlxq/aiL2EjZHxHOYK6pjaq9wPMDgDtql1HRRXg0n/52GzY=
    skip_cleanup: true
    on:
      tags: true
      repo: speelpleinwerking-com/protobufs

  - provider: pages
    skip_cleanup: true
    github_token:
      secure: "O5c+k0lXQAwVptYwPLy2a3iThw+o/Sx/qm4l+4zliga0505tNmjKmp6V+OR7A4RTVfRd5kAad5vfq8U+qMQE4iTe7mcxTCTZL3Kdq6ZExa5VJ+5Qbt7ffp2GdGMAcY/7QHybGctNb7Z4FXyAf8uITV0iyOC9/iXAdbIvYjUqNXZ0BkQgwLyMT4nSUjEb1NNyyiZOmSd5OibhkxLHkFenNi0jGMnYGyLYcEfngo0xI9BPdHlJlGsJaTQsb6hUY1/HPN/lmUEyZLiWTB+xrgMxAo5QJbYJG3r1NEdlHWINTkUFL7B0BiAr4iOnx3Stb2VmM4IHcL5zUZfsJAJqWqljcebH62j55ekzyZWe+R0gCSU+IqbI2YlHNPlyvx6e6p4Xh8mPmp5uemkzBIebNa3fv9X1Xo2eVwe29a9FBeRNjlG2Oo37nMoSM0U7udGEQpISaysoEcdQl6JLVut6IRUiKeyyyR8oJ/ao3gyr4VocgbMzWtyxnkaYIw3/ywdCZTleloBM2QTxCTTxJ0w7UBnD7azwc3hUE3H/GBya4afcs5ez6rOJThjFJ9gtrK3gcg5hu08LSsE/KzLumXoBNh5ESnZKW7fKlYoLVaaojvnF/yStGIpjkKkTx2mmHUFwqSG026TiIkmWoUSSRzKwPAJibxuMrjps5eR7Y9DBxDbZ7v4="
    keep_history: true
    local_dir: doc
    on:
      branch: master

